version: 1.8.1-ci{build}

image: Visual Studio 2017

build_script:
  - cmd: dotnet --info
  - cmd: dotnet restore source
  - cmd: dotnet build source --configuration Debug
  - cmd: dotnet build source --configuration Release

test_script:
  - cmd: set OpenCover=%UserProfile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe
  - cmd: set ReportGenerator=%UserProfile%\.nuget\packages\ReportGenerator\2.5.6\tools\ReportGenerator.exe
  - cmd: if not exist TestResults mkdir TestResults
  - cmd: '"%OpenCover%" -target:dotnet.exe -targetargs:"test source\Handlebars.Test\Handlebars.Test.csproj --configuration Release --framework net461" -searchdirs:source\Handlebars.Test\bin\Release\net461 -output:TestResults\Handlebars.netframework.report.xml -register:user -filter:+[Handlebars]* -returntargetcode -oldstyle'
  - cmd: '"%OpenCover%" -target:dotnet.exe -targetargs:"test source\Handlebars.Test\Handlebars.Test.csproj --configuration Release --framework netcoreapp1.1" -searchdirs:source\Handlebars.Test\bin\Release\netcoreapp1.1 -output:TestResults\Handlebars.netcoreapp.report.xml -register:user -filter:+[Handlebars]* -returntargetcode -oldstyle'
  - cmd: '"%OpenCover%" -target:dotnet.exe -targetargs:"test source\Handlebars.Test\Handlebars.Test.csproj --configuration Release --framework netcoreapp2.0" -searchdirs:source\Handlebars.Test\bin\Release\netcoreapp2.0 -output:TestResults\Handlebars.netcoreapp2.report.xml -register:user -filter:+[Handlebars]* -returntargetcode -oldstyle'
  - cmd: '"%ReportGenerator%" -reports:TestResults\*.report.xml -targetdir:TestResults\report -reporttypes:Badges;Html'

artifacts:
  - path: 'source\**\*.nupkg'
  - path: TestResults
